# Basic site info
title: Rahasia di Balik Lima Angka
description: Kode Pos, Peta, dan Cerita Geospasial Indonesia
lang: id-ID

# Markdown engine
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

# Plugins minimal (aman di GitHub Pages)
plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: false

# Exclude hanya file teknis
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
